### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by chandrab699** [adobe-type-tools/agl-specification#1]
https://partners.adobe.com/public/developer/opentype/index_glyph2.html
above link is broken. Please fix it.

**Comment by kenlunde** [comment]
It seems that this URL became stale a couple of years ago. The document that resolves from the link is about 15 years old. I managed to recover it via the [Wayback Machine](https://web.archive.org/). I need to determine whether it still makes sense to reference this document, and if so, I will host its content here in this repository, or provide it inline.

Many thanks for bringing this to my attention by opening this issue.

**Comment by kenlunde** [comment]
Fixed in Version 2.7 by including the contents of the document inline at the end of Section 6.

**Comment by chandrab699** [comment]
Thank you
